### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by eusthace811**
- set outputFormat to jpeg
- set image quality to medium dataURL = canvas.toDataURL(outputFormat, 0.5);
- Removed newImage  element creation, its not necessary

### CODE REVIEW

**Comment by saniyusuf** [comment]
@jlsuarezs thank you very much. A few questions before we merge. First why do you need to see image quality to 0.5?

**Comment by eusthace811** [comment]
Hi! Thank you!
Because is faster, give a try. :-P

**Comment by saniyusuf** [comment]
@jlsuarezs I agree and it will lead to a smaller file size but also wouldnt it reduce the image quality by 0.5%. This might be critical to some users. Maybe we can find a way of making this configurable where they can pass an attrubute called imagenie-quality that will be used as the quality. If this is not passed 100% wuality is used or if the passed value is not valid 100% is used. Makes sense?

**Comment by eusthace811** [comment]
Yes, good idea!

**Comment by saniyusuf** [comment]
@jlsuarezs  Ok feel free to create this. Also any particular reason for the first point about jpeg?

**Comment by eusthace811** [comment]
Well, again, because is faster and smaller than png.
Ok, let's see!

**Comment by eusthace811** [comment]
What do you think? :-)

**Comment by jeffthompson1971** [comment]
Can this work when i don't use an img tag but have a div and use background-image?  if not how much work would that be?  does it work on all browsers?

**Comment by jeffthompson1971** [comment]
Any plan to make this a bower component?  i tried to do a bower install (this path) and it pulled down just the image.html and a .bower.json file.   no other files were there

**Pull request closed without merging**
